<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>fenrirthegray-traderrestockrefresh</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <DebugType>none</DebugType>
    <Version>1.0.0</Version>
    <GameDir Condition="'$(GameDir)' == ''">C:\dev\spt\stage</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(GameDir)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="$(GameDir)\BepInEx\core\0Harmony.dll" Private="false" />
    <Reference Include="$(GameDir)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(GameDir)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll" Private="false" />
    <Reference Include="$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.dll" Private="false" />
    <Reference Include="$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
  </ItemGroup>

  <Target Name="PackageRelease" AfterTargets="Build">
    <PropertyGroup>
      <RepoDir>$(MSBuildProjectDirectory)/../</RepoDir>
      <ServerDll>$(RepoDir)Server/bin/$(Configuration)/$(AssemblyName).dll</ServerDll>
      <StageDir>$(RepoDir)release/stage/</StageDir>
    </PropertyGroup>
    <Error Condition="!Exists('$(ServerDll)')" Text="$(ServerDll) not found. Build the Server project first." />
    <ItemGroup>
      <ClientFiles Include="$(TargetPath);$(RepoDir)LICENSE" />
      <ServerFiles Include="$(ServerDll);$(RepoDir)LICENSE" />
    </ItemGroup>
    <RemoveDir Directories="$(StageDir)" />
    <Copy SourceFiles="@(ClientFiles)" DestinationFolder="$(StageDir)BepInEx/plugins/$(AssemblyName)/" />
    <Copy SourceFiles="@(ServerFiles)" DestinationFolder="$(StageDir)SPT_Runtime/user/mods/$(AssemblyName)/" />
    <ZipDirectory SourceDirectory="$(StageDir)" DestinationFile="$(RepoDir)release/$(AssemblyName).zip" Overwrite="true" />
    <Copy Condition="Exists('$(GameDir)')" SourceFiles="@(ClientFiles)" DestinationFolder="$(GameDir)/BepInEx/plugins/$(AssemblyName)/" />
    <Copy Condition="Exists('$(GameDir)')" SourceFiles="@(ServerFiles)" DestinationFolder="$(GameDir)/SPT_Runtime/user/mods/$(AssemblyName)/" />
  </Target>

</Project>
