<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <DebugType>none</DebugType>
    <AssemblyName>fenrirthegray-traderrestockrefresh</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" ExcludeAssets="runtime" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" ExcludeAssets="runtime" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.2" ExcludeAssets="runtime" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
